document.body.style.backgroundImage='url(/image/you-dont-know-js.jpg)';
adv=document.querySelector('.adv');
adv.style.display='none';
books=document.querySelectorAll('.book');
books[4].querySelector('h2').querySelector('a').textContent='Книга 3. this и Прототипы Объектов';
books[1].after(books[0]);
books[0].after(books[4]);
books[5].after(books[2]);
chapters2=books[0].querySelector('ul').querySelectorAll('li');
chapters5=books[5].querySelector('ul').querySelectorAll('li');
chapters2[9].after(chapters2[2]);
chapters2[3].after(chapters2[6]);
chapters2[6].after(chapters2[8]);
chapters5[1].after(chapters5[9]);
chapters5[9].after(chapters5[3]);
chapters5[4].after(chapters5[2]);
chapters5[8].before(chapters5[5]);
newChapter=document.createElement('li');
newChapter.textContent='Глава 8: За пределами ES6';
chapList6=books[2].querySelector('ul');
chapList6.appendChild(newChapter);
chapList6.querySelectorAll('li')[8].after(chapList6.querySelectorAll('li')[10]);